### PR TITLE
Splitbutton sample

### LINKED ISSUE #255: Provide SDK sample for splitbutton plugin
Provide SDK sample for new plugin `splitbutton`.

### PR DESCRIPTION
**Pull request by engineering-this**
As new plugin is almost done, we need sample for it, so here it goes.

Closes #255

### CODE REVIEW

**Comment by mlewand** [comment]
Why is this sample highlighting left align for text that has no text-align at all? And is just visually left aligned due to browser default styling?

Repro case:

1. Open Split Button SDK sample.
1. Set the editor content to `<p>Select various</p>`.
1. Put the selection in the middle of that paragraph.

## Expected

Text align split button is not active, since the `text-align` is not applied.

## Actual

Button is active, indicating that the text align is enforced. That would not be the case if the content is placed in a container that has other text alignment.

**Comment by engineering-this** [comment]
@mlewand Thats how our `justify` plugin works. I'm just reusing existing commands.

If you paste source of regular editor with justify plugin following:
```<p style="text-align:left">text</p>
<p>text</p>```
Then both of lines will be treated as aligned to left.

**Comment by mlewand** [comment]
@engineering-this thanks for clarifications, it make sense, this is `justify` issue then.

**Comment by engineering-this** [comment]
I have updated sample.

**Pull request closed without merging**
