### PR TITLE
Turn code sample links into anchor references.

### PR DESCRIPTION
**Pull request by Tade0**
#147, #156.

This (simple) implementation sets the hash upon clicking, which in turn can be used to load the page and automatically open the specified sample.

### CODE REVIEW

**Comment by Reinmar** [comment]
It's ok. Just one issue – the hash should be reset when closing a popup or should not be changed at all when opening it. That's because the URL should not change permanently, cause otherwise people will start sending it.

Second thing – it would be better if the hash was sth like `#sample-1`.

**Comment by Tade0** [comment]
Applied the requested changes.

**Comment by Reinmar** [comment]
Changing the hash scrolls the viewport back to top. To reproduce open and close a popup. This means that we should not change it. Alternatively, please check this solution http://stackoverflow.com/questions/3870057/how-can-i-update-window-location-hash-without-jumping-the-document

**Comment by Tade0** [comment]
We could always use a dummy hash (that doesn't currently point anywhere,  e.g. "_") instead of the "top" hash ("#"). Works just as good, but doesn't increase the complexity.

**Comment by Reinmar** [comment]
To sum up:

1. On link click let's open the dialog **without** changing the link.
2. On page load if the hash contains `sample-\d+`, let's reset the hash (set to empty string) and open a corresponding dialog. In this case we are resetting the hash so the user won't start copying this URL.

This isn't a perfect solution but going into `pushState` we would need much more work to handle state changes. Otherwise we have additional history steps that do nothing.

**Comment by Tade0** [comment]
Ok, only one question remains then: how do the users know that `#sample-\d+` does something?

Or in other words: How does the user find out that including `#-sample-\d+` in the URL opens a dialog on page load?

**Comment by Reinmar** [comment]
> Or in other words: How does the user find out that including #-sample-\d+ in the URL opens a dialog on page load?

That's a different problem - how to share a given code snippet. But that could be done well only with a full approach. However, currently if the user right clicks a link and copies the URL it will work fine.

**Comment by Reinmar** [comment]
Merged with f2011da.

**Pull request closed without merging**
